### ISSUE TITLE
Implement new security pages and alerts

### ISSUE THREAD

**Issue by florianschmidt1994** [option26/quarantine-hero#119]
We've come up with a page with dedicated security warnings for people who help others. Among other things we've also extended our list of warnings from 3 to 4. Necessary changes are

- [x] Show all 4 warnings on landing page
- [x] Implement dedicated security page according to design specs
- [ ] Add dialog that needs to be acknowledged when a user offers its help
- [ ] Add link to security page on success screen
- [x] Add link to security page in emails 

If want to pick up this issue and you need any more information please let me know! 
The design can be found here: https://zpl.io/a81JJqw

**Comment by marko-ignjatovic** [comment]
> Add dialog that needs to be acknowledged when a user offers its help

Hi, I am wondering how dialogs should look like. Maybe something like tailwind dialog where the user have an action button or more like a toast notification (maybe some third party package or custom)?

**Comment by florianschmidt1994** [comment]
Hi Marko ✌️ So far we haven't spent a lot of time discussing what this should look like. I'll ping our designer and let you know as soon as possible.
I believe it would maybe even be something like a checkmark, but as I said we still have to find a good design for this

**Comment by marko-ignjatovic** [comment]
Hi @florianschmidt1994, after I click on that design link I get this:
![you-are-not-invited](https://user-images.githubusercontent.com/31371916/77829264-4a24b300-7121-11ea-91a8-1c48a59922db.png)

**Comment by florianschmidt1994** [comment]
I thought those links would allow public sharing :o 
I'll post some screenshots here as soon as we have them. This might take a day or two, just a heads up. Sorry for the delay

**Comment by Maurice22** [comment]
For visual reference regarding the dialog, please check out #86 .

**Comment by florianschmidt1994** [comment]
Waiting for #153 to be merged

**Comment by mauriceackel** [comment]
Closing as not relevant anymore.
