### ISSUE TITLE
Enhance emails with "report post" feature

### ISSUE THREAD

**Issue by jagaSto** [option26/quarantine-hero#218]
We enhance the emails we currently sent out to users in which we inform them about new help postings in their area with the possibility to report the post as malicious, or add a hint that indicates that it is possible to report said entry as malicious on the website (users suggested this before)

**Comment by Maurice22** [comment]
We merged PR #236 as a precondition for this information to be included in the email. @florianschmidt1994 will update the email template soon to add a text along the lines of "Wenn Du glaubst, dass dieses Inserat unangemessene Inhalte enthält, kannst du es <hier>(use link from email template) melden."

**Comment by jagaSto** [comment]
sendigrid:

```
<div style="font-family: inherit"><br></div>
<div style="font-family: inherit; line-height: 1.5">Wenn Du glaubst, dass dieses Inserat unangemessene Inhalte enthält, kannst du es <a href="{{{reportLink}}}">hier</a> melden.</div>
<div style="font-family: inherit"><br></div>
```

**Comment by jagaSto** [comment]
<img width="643" alt="Screenshot 2020-06-27 at 13 24 45" src="https://user-images.githubusercontent.com/20641332/85921068-92b35000-b879-11ea-9945-6949a95c2f1a.png">

**Comment by jagaSto** [comment]
done!
