### ISSUE TITLE
Enhance email template to contain information about "solved posts" feature

### ISSUE THREAD

**Issue by jagaSto** [option26/quarantine-hero#245]
* indicate in emails to authors of ask-for-help entries that they can set their listings to solved
* we could also think about sending emails to all previous authors to set their posts to solved, maybe even ask them at the same time if they need help again, or similar

**Comment by mauriceackel** [comment]
@jagaSto What is the current state here?

**Comment by jagaSto** [comment]
Good question, never really got tackled to due missing sendgrid permissions. Probably a ticket also for the hackathon! @mauriceackel

**Comment by jagaSto** [comment]
<img width="278" alt="Screenshot 2020-06-27 at 14 28 27" src="https://user-images.githubusercontent.com/20641332/85922294-79fb6800-b882-11ea-9e78-5d842f093285.png">

Current wording already sufficiently indicates this feature --> closed
