### ISSUE TITLE
Asks-for-help migration

### ISSUE THREAD

**Issue by tgraupne** [option26/quarantine-hero#273]
Prior to our collaboration, the matching process in the Facebook group #Coronahilfe was a manual process, based on a public google sheet with asks-for-help and help-offers.

After implementing our special signup page and routing all future requests through us, we should migrate existing and open asks-for-help from that google sheet.

**Comment by Maurice22** [comment]
Are there any legal concern we have to take care of? I.e. ask the people for their consent with our privacy policy first?

**Comment by mauriceackel** [comment]
@tgraupne Are we still going to do this or is it irrelevant by now?

**Comment by tgraupne** [comment]
i guess that is not important anymore 👍
