### ISSUE TITLE
Correct formatDistance internationalization

### ISSUE THREAD

**Issue by mauriceackel** [option26/quarantine-hero#276]
Starting new issue, related to #271 

Concerns Entry.jsx and Responses.jsx

Currently, we don't use the language identified by i18n for internationalizing the string returned by date-fns. As @jakob-ed pointed out, we have to pass a locale object of date-fns to the formatDistance function.

One solution could be the following helper function that converts i18n language strings to date-fns locales:

```
import * as locales from 'date-fns/locale';
import { enUS } from 'date-fns/locale';
import i18next from 'i18next';

const { languages } = i18next;
const getLocale = (l) => {
  for (let i = 0; i < l.length; i += 1) {
    const locale = locales[l[i].replace('-', '')]
    if (locale) {
      return locale;
    }
  }
  return enUS;
};
```

**Comment by jakob-ed** [comment]
I can take this one. I would put a helper function simiilar to the one you proposed into a new file in `./utils` and call that from `Entry.jsx` and `Response.jsx`.
