### ISSUE TITLE
Find a way to keep up-to-date with sentry error reporting

### ISSUE THREAD

**Issue by florianschmidt1994** [option26/quarantine-hero#289]
It feels like some issues might be going unnoticed and we should find a way to keep up-to-date with this

**Comment by kenodressel** [comment]
We should also check other services:

- [ ] Sendgrid
- [ ] Twilio
- [ ] Firebase

**Comment by kenodressel** [comment]
For Sentry I propose the following:
`Send Alerts for Issues that come up more than 20 times in a single day`

**Comment by mauriceackel** [comment]
@kenodressel Can this be closed?
