### ISSUE TITLE
Partner Page

### ISSUE THREAD

**Issue by mauriceackel** [option26/quarantine-hero#315]
<img width="278" alt="Bildschirmfoto 2020-06-04 um 10 06 38" src="https://user-images.githubusercontent.com/20804369/83906749-703f8280-a764-11ea-8559-f97545887999.png">

**Comment by milenasoga** [comment]
Partner und Kooperationen
Covid-19 hat in den vergangenen Monaten viele Lebensbereiche beeinflusst und eingeschränkt. Glücklicherweise gibt es viele Initiativen, die gerade in dieser Zeit auf unterschiedliche Arten Mitmenschen unterstützen möchten. Auf dieser Seite findet Ihr Organisationen, die wir unterstützenswert finden, die uns unterstützen und/oder mit denen wir zusammenarbeiten. 

Gesellschaft & Soziales 
Tafelhilfe
Die Tafelhilfe bringt Tafeln und Freiwillige zusammen. Da gerade jetzt bei vielen Tafeln Freiwillige weggefallen sind, die zum Beispiel zu Risikogruppen gehören, hat sich diese Initiative gegründet, um die wichtige Arbeit der Tafeln zu untersützen.
Zusammen gegen Corona
Auf der Seite ZusammenGegenCorona des Bundesministeriums für Gesundheit sind Informationen und Hilfsangebote zusammengetragen - mit dem Ziel der gegenseitigen Unterstützung. QuarantäneHeld*innen ist Teil dieser Initiative.
Maskeauf
Die Aktion #maskeauf macht darauf aufmerksam, wie wichtig das Tragen einer Maske für den Schutz unserer Mitmenschen ist und stellt verschiedene Näh- und Bastelanleitungen bereit. 
DasLandHilft
Die Seite DasLandHilft vermittelt in Kooperation mit dem Bundesministerium für Ernährung und Landwirtschaft Arbeitskräfte an Landwirtschaftsbetriebe, die coronabedingten Arbeitskräftemangel verzeichnen.

Unterstützer*innen
Blynk
Die Agentur Blynk, die auf Videoproduktionen von Imagefilmen bis hin zu 3D-Animationen spezialisiert ist, hat unsere Initiative mit einem wundervollem Erklärvideo unterstützt. Das Video findet ihr hier.
Twilio
Die Cloud Communications Plattform Twilio supportet uns beim Betrieb unserer Hotline - damit wir für Euch auch telefonisch erreichbar sind.
Google
Google unterstützt uns beim Betreiben der Website und hilft uns, dass wir auch beim größten Ansturm erreichbar bleiben. 

https://docs.google.com/document/d/1HlJlJw3lyPO_FHJhfsVX0of7hOaZuaC7nV9kr1cejBI/edit#
