### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by jagaSto** [option26/quarantine-hero#325]
searching for `Nachbarschaftshilfe corona` on google currently does not show quarantänehelden on the first spot ;) we should see what we can do about this!

**Comment by jagaSto** [comment]
Lighthouse report:

<img width="729" alt="Screenshot 2020-10-05 at 21 44 21" src="https://user-images.githubusercontent.com/20641332/95124574-ef18ec00-0753-11eb-8169-9b3d6a146535.png">

**Comment by jagaSto** [comment]
https://medium.com/@prestonwallace/3-ways-improve-react-seo-without-isomorphic-app-a6354595e400 --> meta tag description could do wonders:

<img width="901" alt="Screenshot 2020-10-05 at 21 43 15" src="https://user-images.githubusercontent.com/20641332/95124741-2b4c4c80-0754-11eb-8c66-7adb52ae645b.png">

<img width="879" alt="Screenshot 2020-10-05 at 21 43 08" src="https://user-images.githubusercontent.com/20641332/95124746-2e473d00-0754-11eb-9c93-7ee914e86673.png">

**Comment by jagaSto** [comment]
also interesting: https://support.google.com/webmasters/answer/9008080#meta_tag_verification

**Comment by jagaSto** [comment]
https://support.google.com/webmasters/answer/9274190?hl=en

**Comment by jagaSto** [comment]
https://support.google.com/webmasters/answer/7451184?ref_topic=9268559

**Comment by mauriceackel** [comment]
@jagaSto Can we close this?

**Comment by jagaSto** [comment]
sure
