### ISSUE TITLE
Delete function timeouts

### ISSUE THREAD

**Issue by jagaSto** [option26/quarantine-hero#328]
* @kenodressel forgot to take notes here, could you elaborate? 😇

**Comment by kenodressel** [comment]
Fairly simple: The deleteCreate function on prod times out after 60 seconds when its triggered.

**Comment by mauriceackel** [comment]
I just checked the logs, 4 executions in December, no fails? Is this still relevant?

**Comment by jagaSto** [comment]
done with #401
