### ISSUE TITLE
Move hotline-related HTTP functions into repository

### ISSUE THREAD

**Issue by jagaSto** [option26/quarantine-hero#339]
* configureGoogleApiAccess
* handleVoicemail
* oauthCallback

The source code for these functions currently does not live in the repository. We should move them here for better maintainability (e.g., updating them to node 10)

@florianschmidt1994 we assume that they currently live locally on your machine, could you move them here? :)

**Comment by florianschmidt1994** [comment]
I'll look into it

**Comment by mauriceackel** [comment]
@florianschmidt1994 I think the functions Janik is referring to (configureGoogleApiAccess, handleVoicemail, oauthCallback) are no longer needed. I think we can close this. Please confirm.

**Comment by florianschmidt1994** [comment]
You are right. Those are remains from experiments we did with a different sign-up flow (OAuth) that we are not using now anymore.
