### ISSUE TITLE
exchange text for mobile version

### ISSUE THREAD

**Issue by milenasoga** [option26/quarantine-hero#368]
The "Ich brauche Hilfe" and "Ich möchte helfen" buttons need to be repositioned so that they show up above the corresponding textbox (mobile version)

**Comment by kenodressel** [comment]
I think our homepage is due for a redesign tbh. There is too much text and nobody will read it on the mobile version. We should consider shortening the text instead of moving the button out of view.

**Comment by milenasoga** [comment]
update texts on both web and mobile versions on landing page: https://docs.google.com/document/d/1Mhe6NmDaopakWTqGbD4Pp5mWwMM8-plHohFYbJyS1xk/edit#
