### ISSUE TITLE
delete links on security page

### ISSUE THREAD

**Issue by milenasoga** [option26/quarantine-hero#370]
Kontaktverbot Bundesregierung:
https://www.bundesregierung.de/resource/blob/975226/1733246/e6d6ae0e89a7ffea1ebf6f32cf472736/2020-03-22-mpk-data.pdf?download=1

Ausgangssperre Österreich
https://www.sozialministerium.at/dam/jcr:aca0d8db-a2c6-46bd-bf07-b04cd187fd84/Verordnung_V20200319_Ansicht.pdf

Verordnung des Schweizerischen Bundesrats über Maßnahmen des Coronavirus
https://www.admin.ch/opc/de/classified-compilation/20200744/index.html

**Comment by mauriceackel** [comment]
Done
