### ISSUE TITLE
No emails received or emails delayed

### ISSUE THREAD

**Issue by mauriceackel** [option26/quarantine-hero#38]
It seems as if the signup emails are not received (potentially flagged as SPAM) by t-online mail.

We might need to improve our mail reputation (i.e. create SPF record, etc.)

**Comment by wiredancer** [comment]
I received confirmation emails on my GMX email account multiple hours late yesterday, and the confirmation link was already expired when I saw them.

Furthermore, the first one was classified as spam by GMX, the following ones in Inbox.

**Comment by Maurice22** [comment]
Task: Check sendgrid doku for tips how to increase mail reputation

**Comment by jagaSto** [comment]
I also experienced the same for one of my gmx testing mails when trying to do a password reset, the first mail did not arrive at all. After requesting a reset link for the second time, it arrived instantly 🤷‍♂

**Comment by florianschmidt1994** [comment]
I've setup firebase to use the sendgrid smtp server in staging. For an icloud email this worked for me, but the email landed in the spam inbox. For gmail it worked flawlessly. @jagaSto could you create a test account with gmx on staging and check the behaviour?

**Comment by Maurice22** [comment]
@MissCauchy , can you check with GMX pls?

**Comment by mauriceackel** [comment]
We are using sendgrid to send emails in production now as well. We won't look into this in more detail for now. Closing.
